apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lmkk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-lmkk@sha256:ebf2bd71951ddcd4b7806287380682752ef3de538ef2368be6585c4ce513fcff
        name: my-nodejs
        resources: {}
status: {}
